### ISSUE TITLE
No Vagrantfile found

### ISSUE THREAD

**Issue by mattalexx** [Sparkcentral/PSRedis#12]
The instructions for running integration tests mention "After installing all of these, execute the following in the project root to provision the machines: vagrant up". But when I run `vagrant up`, I get "A Vagrant environment or target machine is required to run this command. Run `vagrant init` to create a new Vagrant environment."

**Comment by jamescauwelier** [comment]
Try again @mattalexx and let me know how it goes?

**Comment by mattalexx** [comment]
I got this:

	==> redis1: Checking for guest additions in VM...
	==> redis1: Checking for host entries
	==> redis1: Configuring and enabling network interfaces...
	==> redis1: Mounting shared folders...
	    redis1: /vagrant => /Users/alexandma/Projects/PSRedis
	==> redis1: Running provisioner: ansible...
	The executable 'ansible-playbook' Vagrant is trying to run was not
	found in the PATH variable. This is an error. Please verify
	this software is installed and on the path.

**Comment by jamescauwelier** [comment]
Thank you for the additional info.  I'll check it out this evening!

**Comment by jamescauwelier** [comment]
@mattalexx Do you have ansible installed on your machine?

See http://docs.ansible.com/intro_installation.html

**Comment by mattalexx** [comment]
Oh, I was under the impressions that Ansible works like Puppet in that it only needs to be installed in the guest, but I was wrong:

http://docs.vagrantup.com/v2/provisioning/ansible.html
