### ISSUE TITLE
"Argument 1 passed to PSRedis\MasterDiscovery::setBackoffObserver() must be an instance of PSRedis\callable, array given"

### ISSUE THREAD

**Issue by mattalexx** [Sparkcentral/PSRedis#13]
.........E.

    Time: 1.92 minutes, Memory: 15.75Mb

    There was 1 error:

    1) PSRedis\MasterDiscoveryTest::testDiscoveryWithBackoffWorksWithSentinelsTemporarilyUnreachable
    Argument 1 passed to PSRedis\MasterDiscovery::setBackoffObserver() must be an instance of PSRedis\callable, array given, called in /Users/alexandma/Projects/PSRedis/tests/integration/PSRedis/MasterDiscoveryTest.php on line 149 and defined

    /Users/alexandma/Projects/PSRedis/lib/PSRedis/MasterDiscovery.php:159
    /Users/alexandma/Projects/PSRedis/tests/integration/PSRedis/MasterDiscoveryTest.php:149

    FAILURES!
    Tests: 11, Assertions: 26, Errors: 1.

**Comment by jamescauwelier** [comment]
What version and branch are you working on?  Both develop and master seem to be running fine here.  Can you give a bit more detail?  Where are you running this code?  On what version of PHP, etc?

**Comment by jamescauwelier** [comment]
@mattalexx to give some more details on this issue, see http://php.net/manual/en/language.types.callable.php

I quote: "Callbacks can be denoted by callable type hint as of PHP 5.4"

This basically means I need to update the composer file to require this.  If you don't want to update your version of PHP you can fork the repo and remove the type hint of 'callable'.  Does this answer your question?

**Comment by jamescauwelier** [comment]
FYI, [this commit](https://github.com/Sparkcentral/PSRedis/commit/992fb0c1055d5fe14f9273b4a622c1b36759d0d1) updates the minimum requirements for PHP version.

**Comment by mattalexx** [comment]
Sure, thanks.
